FA.JustBlog/FA.JustBlog/Areas/Admin/Controllers/CommentController.cs
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using FA.JustBlog.Core.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_BlogOwner + ", " + SD.Role_Contributor)]
    public class CommentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CommentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IList<Comment> cmtList = _unitOfWork.CommentRepository.GetAll(includeProperties: "Post");
            return View(cmtList);
        }
        [Authorize(Roles = SD.Role_BlogOwner)]
        public IActionResult Create()
        {
            CommentVM commentVM = new()
            {
                Comment = new(),
                PostList = _unitOfWork.PostRepository.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Title,
                    Value = u.Id.ToString()
                })
            };
            return View(commentVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CommentVM obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CommentRepository.Add(obj.Comment);
                _unitOfWork.Save();
                TempData["success"] = "Comment created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Edit(int id)
        {
            CommentVM commentVM = new()
            {
                Comment = _unitOfWork.CommentRepository.Find(id),
                PostList = _unitOfWork.PostRepository.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Title,
                    Value = u.Id.ToString()
                })
            };
            return View(commentVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CommentVM request)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.CommentRepository.Update(request.Comment);
                _unitOfWork.Save();
                TempData["success"] = "Comment updated successfully";
                return RedirectToAction("Index");
            }

            return View(request);
        }
        //GET
        [Authorize(Roles = SD.Role_BlogOwner)]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var commentFromDb = _unitOfWork.CommentRepository.GetFirstOrDefault(c => c.Id == id, "Post");
            if (commentFromDb == null)
            {
                return NotFound();
            }
            return View(commentFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.CommentRepository.GetFirstOrDefault(c => c.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.CommentRepository.Delete(obj);
            _unitOfWork.Save();
            TempData["success"] = "Comment deleted successfully.";
            return RedirectToAction("Index");
        }
    }
}

FA.JustBlog/FA.JustBlog/Areas/User/Controllers/PostController.cs
using FA.JustBlog.Core.Data;
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FA.JustBlog.Controllers
{
    [Area("User")]
    public class PostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PostController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var postList = _unitOfWork.PostRepository.GetAll(includeProperties: "Category");
            return View(postList);
        }
        public IActionResult Details(int id)
        {
            var postFromDb = _unitOfWork.PostRepository.Find(id);
            return View(postFromDb);
        }
        [Route("Post/{year}/{month}/{title}")]
        public IActionResult Details(int year, int month, string title)
        {
            var postFromDb = _unitOfWork.PostRepository.FindPost(year, month, title);
            return View(postFromDb);
        }
        public IList<Post> LastestPost()
        {
            var latestPosts = _unitOfWork.PostRepository.GetLatestPost(3);
            return latestPosts;
        }
        public IActionResult MostViewedPosts()
        {
            ViewData["MostViewedPosts"] = _unitOfWork.PostRepository.GetMostViewedPost(3);
            return PartialView("_Layout");
        }

        public IActionResult GetPostsByCategory(string category)
        {
            var postList = _unitOfWork.PostRepository.GetAll(u => u.Category.Name == category, "Category");
            return View("Index", postList);
        }
        public IActionResult GetPostsByTag(string tag)
        {
            var postList = _unitOfWork.PostRepository.GetPostsByTag(tag);
            return View("Index", postList);
        }
    }
}

FA.JustBlog/FA.JustBlog/Areas/User/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    [Area("User")]
    public class TagController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FA.JustBlog/FA.JustBlog/Views/Shared/_Layout.cshtml
@using FA.JustBlog.Core.Infrastructures
@inject IUnitOfWork unitOfWork

@{
    ViewData["PAcute"] = "Phanh Cute";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FA.JustBlog</title>
    <link rel="stylesheet" href="~/css/ThemeForBlog.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FA.JustBlog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="User" asp-controller="Home" asp-action="Index">FA.JustBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="User" asp-controller="Post" asp-action="Index">Post</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
                            <div class="dropdown-menu">
                                @foreach (var item in unitOfWork.CategoryRepository.GetAll())
                                {
                                    <a class="dropdown-item" asp-area="User" asp-controller="Post" asp-action="GetPostsByCategory" asp-route-category="@item.Name">@item.Name</a>
                                }
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Post" asp-action="Index">Post</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Tag" asp-action="Index">Tag</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Comment" asp-action="Index">Comment</a>
                            </div>
                        </li>

                    </ul>
                <partial name="_LoginPartial"></partial>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @*<div class = "row">
                <div class="col-8">
                @RenderBody()
                </div>
                <div class="col-4 pt-5">
                <partial name="_PartialAboutCard.cshtml"></partial>
                <partial name="_ListPosts" model="@unitOfWork.PostRepository.GetLatestPost(3)" view-data="ViewData"></partial>
                <partial name="_ListPosts" model="@unitOfWork.PostRepository.GetMostViewedPost(3)"></partial>
                </div>
                </div>*@
        </main>
    </div>
    <partial name="_PartialFooter"></partial>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FA.JustBlog/FA.JustBlog/Views/Shared/_LayoutAdmin.cshtml
@using FA.JustBlog.Core.Infrastructures
@inject IUnitOfWork unitOfWork

@{
    ViewData["PAcute"] = "Phanh Cute";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FA.JustBlog</title>
    <link rel="stylesheet" href="~/css/AdminTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FA.JustBlog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="User" asp-controller="Home" asp-action="Index">FA.JustBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="User" asp-controller="Post" asp-action="Index">Post</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
                            <div class="dropdown-menu">
                                @foreach (var item in unitOfWork.CategoryRepository.GetAll())
                                {
                                    <a class="dropdown-item" asp-area="User" asp-controller="Post" asp-action="GetPostsByCategory" asp-route-category="@item.Name">@item.Name</a>
                                }
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Post" asp-action="Index">Post</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Tag" asp-action="Index">Tag</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Comment" asp-action="Index">Comment</a>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <partial name="_PartialFooter"></partial>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FA.JustBlog/FA.JustBlog/Views/Shared/_ListPosts.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Post>


@if (Model.Count() > 0)
{
    @foreach (var item in Model)
    {
        <h3 class="text-info">
            <a asp-area="User" asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" style="text-decoration:none">@item.Title</a>
        </h3>
        <div>
            <p>Posted @item.PostedOn with rate @item.Rate.ToString("0.0") by @item.RateCount view(s)</p>
            <p class="card-text">@item.ShortDescription</p>
        </div>
        <br />
    }
}
else
{
    <p>No author exists...</p>
}

FA.JustBlog/FA.JustBlog/Views/Shared/_PartialAboutCard.cshtml
<div class="card">
    <h3 class="card-header text-info">
        About Me!
    </h3>
    <div class="card-body">
        <p>My name is Phanh</p>
    </div>
</div>

FA.JustBlog/FA.JustBlog/Views/Shared/_PartialFooter.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - FA.JustBlog - <a asp-area="User" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>